language: python
branches:
  only:
  - master
matrix:
  include:
  - name: "3.7 pytest"
    # should be 3.7 but Travis CI doesn't have that!
    python: "3.6"
script: bash ./run-test.sh
git:
  depth: 1