# Travis CI configuration file for coverlovin2
#
# docs:
#   https://docs.travis-ci.com/user/languages/python/ (https://archive.vn/w3tp5)
#   https://docs.travis-ci.com/user/reference/linux
# schema:
#   https://raw.githubusercontent.com/travis-ci/travis-yml/ddfadc679cc80478b84f7b3cffde7cef991eace6/schema.json
---
language: python
os: linux
branches:
  only:
    - master
    - travis
notifications:
  email: true
git:
  depth: 1
matrix:
  include:
    - name: "3.8 pytest"
      python: 3.8
      dist: xenial
    - name: "3.9 pytest"
      python: 3.9
      dist: bionic
    - name: "3.10 pytest"
      python: 3.10
      dist: focal
    - name: "3.11 pytest"
      python: 3.11
      dist: jammy
install:
  - pip install --disable-pip-version-check pipenv
  - pipenv install --dev --verbose
  # Issue #23
  - pip list -vvv
  - pip install --disable-pip-version-check pipdeptree
  - pipdeptree
before_script:
  # the executable bit is not set on scripts under `tools/`, so force it
  - chmod -vR +x,-w -- ./tools/
script:
  # sanity check coverlovin2.py can start
  - python ./coverlovin2/app.py --version
  - ./tools/yamllint.sh
  - ./tools/pytest-run.sh
    --cov=./coverlovin2/ --cov-config=./.coveragerc --cov-report=xml
    --log-cli-level=DEBUG --verbosity=1
  - ./tools/build-install-test.sh
after_success:
  - coveralls
  # upload coverage report to codecov.io
  # requires setting secret environment variable COVERALLS_REPO_TOKEN within
  # Travis -> Settings -> Environment Variables
  - codecov --file coverage.xml
