language: python
branches:
  only:
  - master
matrix:
  include:
  - name: "3.7 pytest"
    python: "3.7"
    dist: xenial  # currently required for Python 3.7 on Travis CI
script: bash ./run-test.sh
git:
  depth: 1