language: python
#python:
#  - "3.7"  # running this fails
#  - "3.6"
branches:
  only:
  - master
notifications:
  email: true
matrix:
  include:
  - name: "3.7 pytest"
    python: "3.7"
    dist: xenial  # currently required for Python 3.7 on Travis CI
  - name: "3.6 check version failure"
    python: "3.6"
# the executable bit is not set on scripts under `tools/`, so force it
before_script: chmod -vR +x,-w -- ./tools/
script: ./tools/test-travisci.sh
git:
  depth: 1
