# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  prep_cache:
    docker:
      # see https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          command: |
            shopt
            echo
            env | sort
            echo
            pwd
            echo
            uname -a
            echo
            ls -la
            echo
            chmod -vR +x,-w -- ./tools/
            echo
            python -m pip install --user --upgrade pip
            python -m pip install pipenv
            echo
            pipenv --version
            echo
            mkdir -v -- .pipenv
            export PIPENV_CACHE_DIR=.pipenv
            pipenv install --dev
      - save_cache:
          name: cache of checkout, chmod, pipenv installs
          paths:
            - .
            - ~/.local/
          key: prep_cache-{{ .Branch }}-{{ .Revision }}
  test_python36:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - restore_cache:
          key: prep_cache-{{ .Branch }}-{{ .Revision }}
      - run: tools/test-python36.sh
  test_pytest:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - restore_cache:
          key: prep_cache-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            pwd
            export PIPENV_CACHE_DIR=.pipenv
            pipenv run python3 -m pytest -v coverlovin2/test
  build_pypi:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - restore_cache:
          key: prep_cache-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            pwd
            export PIPENV_CACHE_DIR=.pipenv
            pipenv run pip install --upgrade setuptools wheel
            pipenv run bash tools/build-install-test.sh
workflows:
  version: 2
  workflow_prep_test_build:
    jobs:
      - prep_cache
      - test_python36:
          requires:
          - prep_cache
      - test_pytest:
          requires:
          - prep_cache
      - build_pypi:
          requires:
          - prep_cache
          - test_python36
          - test_pytest
