# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  prep_cache:
    docker:
      # see https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          command: |
            env | sort
            echo
            pwd
            echo
            uname -a
            echo
            ls -la
            echo
            chmod -vR +x -- tools
            python -m pip install --upgrade pip
            python -m pip install pipenv
            pipenv --version
            mkdir .pipenv
            export PIPENV_CACHE_DIR=.pipenv
            pipenv install --dev
      - save_cache:
          name: cache of checkout, chmod, pipenv installs
          paths:
            - .
          key: prep_cache-{{ .Branch }}-{{ .BuildNum }}-{{ .Revision }}
  test_python36:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - restore_cache:
          key: prep_cache-{{ .Branch }}-{{ .BuildNum }}-{{ .Revision }}
      - run: tools/test-python36.sh
  test_pytest:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - restore_cache:
          key: prep_cache-{{ .Branch }}-{{ .BuildNum }}-{{ .Revision }}
      - run:
          command: |
            export PIPENV_CACHE_DIR=.pipenv
            pipenv shell
            python3 -m pytest -v coverlovin2/test
  build_pypi:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - restore_cache:
          key: prep_cache-{{ .Branch }}-{{ .BuildNum }}-{{ .Revision }}
      - run:
          command: |
            export PIPENV_CACHE_DIR=.pipenv
            pipenv shell
            tools/build-install-test.sh
workflows:
  version: 2
  workflow_prep_test_build:
    jobs:
      - prep_cache
      - test_python36:
          requires:
          - prep_cache
      - test_pytest:
          requires:
          - prep_cache
      - build_pypi:
          requires:
          - prep_cache
          - test_pytest