# Python CircleCI 2.1 configuration file
#
# environment variable CACHE_VERSION value is set at
# https://circleci.com/gh/jtmoon79/coverlovin2/edit#env-vars
#
---
version: 2.1
jobs:
  prep_workspace_cache:
    docker:
      # see https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          command: |
            set -x
            echo -e "\n\n### record information about the shell context\n\n"
            pwd
            shopt
            env | sort
            uname -a
            ls -la
            which python
            python --version
            if which pipenv 2>/dev/null; then pipenv --version; fi
            echo -e "\n\n### prepare the jobs workspace\n\n"
            chmod -vR +x,-w -- ./tools/
            echo -e "\n\n### prepare the cache\n\n"
            python -m pip install --user --upgrade pip
            python -m pip install --user pipenv
            pipenv --version
            export PIPENV_CACHE_DIR=~/.pipenv-cache
            export PIPENV_VIRTUALENV=~/.pipenv-venv
            export WORKON_HOME=~/.pipenv-venv
            mkdir -v -- "${PIPENV_CACHE_DIR}" "${PIPENV_VIRTUALENV}" "${WORKON_HOME}"
            echo -e 'export PIPENV_CACHE_DIR=~/.pipenv-cache' >> "${BASH_ENV}"
            echo -e 'export PIPENV_VIRTUALENV=~/.pipenv-venv' >> "${BASH_ENV}"
            echo -e 'export WORKON_HOME=~/.pipenv-venv' >> "${BASH_ENV}"
            pipenv install --dev
            # make really sure setuptools and wheel is the latest
            pipenv run pip install --upgrade setuptools wheel
      - save_cache:
          name: cache of pipenv installs
          key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ arch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.pipenv
            - ~/.pipenv-venv
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  test_python36:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ arch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            set -x
            pwd
            env | sort
            python -m pip install --user pipenv
            python -m pipenv --where
            python -m pipenv --venv
            python -m pipenv --py
            python -m pipenv --python $(which python) run tools/test-python36.sh
  test_pytest:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ arch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            set -x
            pwd
            python -m pip install --user pipenv
            export PIPENV_CACHE_DIR=~/.pipenv
            export PIPENV_VIRTUALENV=~/.pipenv-venv
            export WORKON_HOME=${PIPENV_VIRTUALENV}
            pipenv run python3 -m pytest -v coverlovin2/test
  build_pypi:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ arch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            set -x
            pwd
            python -m pip install --user pipenv
            export PIPENV_CACHE_DIR=~/.pipenv
            export PIPENV_VIRTUALENV=~/.pipenv-venv
            export WORKON_HOME=${PIPENV_VIRTUALENV}
            pipenv run bash tools/build-install-test.sh
workflows:
  version: 2
  workflow_prep_test_build:
    jobs:
      - prep_workspace_cache
      - test_python36:
          requires:
            - prep_workspace_cache
      - test_pytest:
          requires:
            - prep_workspace_cache
      - build_pypi:
          requires:
            - prep_workspace_cache
            - test_python36
            - test_pytest
